server:
    port: 3002
log:
    level: info
    service: order
postgres:
    host: postgres
    port: 5432
    dbname: postgres
    user: postgres
    password: postgres
    sslmode: disable
rabbitmq:
    url: amqp://guest:guest@localhost:5672/
