server:
    port: 3001
log:
    level: debug
    service: shop
postgres:
    host: postgres
    port: 5432
    dbname: postgres
    user: postgres
    password: postgres
    sslmode: disable
grpc:
    payment:
        addr: payment:3004
