server:
    port: 3001
log:
    level: info
    service: payment
omise:
    public_key: omisepublickey
    secret_key: omisesecretkey
postgres:
    host: postgres
    port: 5432
    dbname: postgres
    user: postgres
    password: postgres
    sslmode: disable
rabbitmq:
    url: amqp://guest:guest@localhost:5672/
