server:
  port: 3003
log:
  level: info
  service: auth
oauth:
  client_id:
  client_secret:
  redirect_url: http://localhost:8080/api/v1/auth/google/callback
postgres:
  host: localhost
  port: 5432
  dbname: postgres
  user: postgres
  password: postgres
  sslmode: disable
redis:
  address: localhost:6379
  password:
  database: 0
grpc:
  user:
    addr: localhost:3000
