// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: auth/pkg/authproto/auth.proto

package authproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	ExchangeAuthCode(ctx context.Context, in *ExchangeAuthCodeReq, opts ...grpc.CallOption) (*ExchangeAuthCodeResp, error)
	VerifyAccessToken(ctx context.Context, in *VerifyAccessTokenReq, opts ...grpc.CallOption) (*VerifyAccessTokenResp, error)
	RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenReq, opts ...grpc.CallOption) (*RefreshAccessTokenResp, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) ExchangeAuthCode(ctx context.Context, in *ExchangeAuthCodeReq, opts ...grpc.CallOption) (*ExchangeAuthCodeResp, error) {
	out := new(ExchangeAuthCodeResp)
	err := c.cc.Invoke(ctx, "/auth.Auth/ExchangeAuthCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) VerifyAccessToken(ctx context.Context, in *VerifyAccessTokenReq, opts ...grpc.CallOption) (*VerifyAccessTokenResp, error) {
	out := new(VerifyAccessTokenResp)
	err := c.cc.Invoke(ctx, "/auth.Auth/VerifyAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenReq, opts ...grpc.CallOption) (*RefreshAccessTokenResp, error) {
	out := new(RefreshAccessTokenResp)
	err := c.cc.Invoke(ctx, "/auth.Auth/RefreshAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	ExchangeAuthCode(context.Context, *ExchangeAuthCodeReq) (*ExchangeAuthCodeResp, error)
	VerifyAccessToken(context.Context, *VerifyAccessTokenReq) (*VerifyAccessTokenResp, error)
	RefreshAccessToken(context.Context, *RefreshAccessTokenReq) (*RefreshAccessTokenResp, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) ExchangeAuthCode(context.Context, *ExchangeAuthCodeReq) (*ExchangeAuthCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeAuthCode not implemented")
}
func (UnimplementedAuthServer) VerifyAccessToken(context.Context, *VerifyAccessTokenReq) (*VerifyAccessTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAccessToken not implemented")
}
func (UnimplementedAuthServer) RefreshAccessToken(context.Context, *RefreshAccessTokenReq) (*RefreshAccessTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshAccessToken not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_ExchangeAuthCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeAuthCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ExchangeAuthCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/ExchangeAuthCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ExchangeAuthCode(ctx, req.(*ExchangeAuthCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_VerifyAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAccessTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).VerifyAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/VerifyAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).VerifyAccessToken(ctx, req.(*VerifyAccessTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RefreshAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAccessTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RefreshAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/RefreshAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RefreshAccessToken(ctx, req.(*RefreshAccessTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeAuthCode",
			Handler:    _Auth_ExchangeAuthCode_Handler,
		},
		{
			MethodName: "VerifyAccessToken",
			Handler:    _Auth_VerifyAccessToken_Handler,
		},
		{
			MethodName: "RefreshAccessToken",
			Handler:    _Auth_RefreshAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/pkg/authproto/auth.proto",
}
