server:
  port: 8080
log:
  level: info
  service: apigateway
grpc:
  user:
    addr: localhost:3000
  auth:
    addr: localhost:3003
oauth:
  client_id:
  client_secret:
  redirect_url: https://localhost:8080/api/v1/auth/google/callback
