server:
  port: 8080
log:
  level: debug
  service: apigateway
grpc:
  user:
    addr: localhost:3000
  shop:
    addr: localhost:3001
  order:
    addr: localhost:3002
  auth:
    addr: localhost:3003
  payment:
    addr: localhost:3004
