server:
  port: 8080
log:
  level: info
  service: apigateway
grpc:
  user:
    addr: localhost:3000
  shop:
    addr: localhost:3001
  order:
    addr: localhost:3002
  auth:
    addr: localhost:3003
  payment:
    addr: localhost:3004
oauth:
  client_id:
  client_secret:
  redirect_url: http://localhost:8080/api/v1/auth/google/callback
